### ISSUE TITLE
Color_continuous_layer does not support range_min and range_max

### ISSUE THREAD

**Issue by connerpate** [CartoDB/cartoframes#1439]
This documentation suggests there is a way to manually define the max and min values for a continuous range:
https://carto.com/developers/cartoframes/reference/#cartoframes-viz-Style

![image](https://user-images.githubusercontent.com/21110478/71739609-ee030900-2e27-11ea-9954-1637903cab70.png)

However, when I try it in my code, I get this error:
_TypeError: color_continuous_layer() got an unexpected keyword argument 'range_min'_

**Comment by makella** [comment]
hi @connerpate! can you tell us what version you are using? the range min/max parameters are available with versions `v1.0b5` and later. thanks!

**Comment by connerpate** [comment]
Hi Mamata,
Looks like it was my error, I got it working using v1.0b6 when I had been using b3 before. Thank you. 
Best,
Conner

**Comment by makella** [comment]
great!!
